name: Publish to pub.dev

on:
  push:
    branches:
      - main
      
jobs:
  publish:
    permissions:
      id-token: write 
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
    #   working-directory: https://github.com/RichardM20/animated_toast